### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by mzf** [ovr/phalcon-module-skeleton#11]
I make fresh install via command
`composer create-project ovr/phalcon-module-skeleton=dev-master /path/to/install`
When i click on any link in top menu link
(example http://phalcon-module-skeleton.loc/frontend/index/getting-started/)
i get apache  error `Object not found!`
And i dont have any .htaccess in public directory. Is this ok?
I use Win7+Apache2+PHP5.5+Phalcon 2.1

**Comment by ovr** [comment]
Hey!

This will be funny, because 3 year later I reply on this Issue😄 

I didnt see it because I am bad manager of my email in-box

Due not enough time and no interest I didn't improve this skeleton and will not do it :(

I am going to ***close this issue and mark this project as archive***

Thanks
