### ISSUE TITLE
Page 404 dont work

### ISSUE THREAD

**Issue by mzf** [ovr/phalcon-module-skeleton#13]
Action `index/index` catch all urls.
Example - `http://phalcon-module-skeleton.loc/sdsdsd/dwfeertwet` show main page

**Comment by ovr** [comment]
Hey!

This will be funny, because 3 year later I reply on this Issue😄 

I didnt see it because I am bad manager of my email in-box

Due not enough time and no interest I didn't improve this skeleton and will not do it :(

I am going to ***close this issue and mark this project as archive***

Thanks
