### ISSUE TITLE
Certificate error on site https://phalcon-module.dmtry.me/ 

### ISSUE THREAD

**Issue by mzf** [ovr/phalcon-module-skeleton#14]
Cant load site  https://phalcon-module.dmtry.me/ 

`
Это соединение является недоверенным

Вы попросили Firefox установить защищённое соединение с phalcon-module.dmtry.me, но мы не можем гарантировать, что это соединение является защищённым.

Обычно, когда вы пытаетесь установить защищённое соединение, сайты предъявляют проверенный идентификатор, служащий доказательством того, что вы направляетесь в нужное место. Однако идентификатор этого сайта не может быть проверен.
Что мне делать?

Если вы обычно без проблем соединяетесь с данным сайтом, эта ошибка может означать, что кто-то пытается подменить этот сайт другим. В этом случае вам не следует продолжать соединение.

Этот сайт использует HTTP Strict Transport Security (HSTS), чтобы указать, что Firefox должен подключаться к нему только через защищённое соединение. В результате, добавление исключения для этого сертификата невозможно.
`

**Comment by ovr** [comment]
Hey @mzf, I am rly sorry, that I didnt see this issue
So, I generated a ssl cert by https://letsencrypt.org/

Thank 🍰 🍥
